### ISSUE TITLE
Regex filters for email validation (domain claiming style)

### ISSUE THREAD

**Issue by nwcell** [adobe/dynamic-workflow#14]
The idea is that some customers will want to limit behavior to certain email domains.  The most robust way to do this would be to add a regex filter that is managed via the config.

**Comment by srtucker** [comment]
I my opinion this would be greatly improved if it could be configured in Workflow designer per recipient rather than a global setting on the app. We have use cases when the requestor can be any email address but the approver must have a specific email domain.

**Comment by nwcell** [comment]
That would be a good feature to have in workflows, for sure.
