### ISSUE TITLE
Fresh install on Digital Ocean, couldn't fetch the workflows from Adobe Sign

### ISSUE THREAD

**Issue by umuur** [adobe/dynamic-workflow#27]
### Expected Behaviour
Dropdown should fill by the Adobe Sign workflows

### Actual Behaviour
Dropdown looks empty. Console throws:
```
(node:8916) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at http://134.122.70.165/api/rest/v5/workflows reason: Unexpected token < in JSON at position 0
    at /root/dynamic-workflow/node_modules/node-fetch/lib/index.js:272:32
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

![image](https://user-images.githubusercontent.com/8915912/87030918-f8dd9280-c1ea-11ea-8128-8e8045141e80.png)

I have 2 sample workflows in my Adobe Sign account. None of them fetched by the Dynamic Workflow.

**Comment by nwcell** [comment]
@umuur, have you been able to run locally?

**Comment by umuur** [comment]
@nwcell unfortunately no. refer:#25

**Comment by nwcell** [comment]
removing, because it's related to the above issue.
